# Generated by Django 5.0.6 on 2024-06-29 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ParsingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_comment='Дата создания сессии', verbose_name='Дата создания сессии')),
                ('file_name', models.CharField(db_comment='Название файла', max_length=256, verbose_name='Название файла')),
                ('link_video', models.TextField(db_comment='Ссылка на видео', verbose_name='Ссылка на видео')),
                ('pool_length', models.CharField(choices=[('25m', '25m'), ('50m', '50m')], db_comment='Длина бассейна', default='25m', max_length=4, verbose_name='Длина бассейна, м')),
                ('swim_length', models.CharField(choices=[('50m', '50m'), ('100m', '100m'), ('200m', '200m'), ('400m', '400m')], db_comment='Длина заплыва', default='100m', max_length=5, verbose_name='Длина заплыва, м')),
            ],
            options={
                'verbose_name': 'сессию парсинга',
                'verbose_name_plural': 'Сессии парсинга',
            },
        ),
        migrations.CreateModel(
            name='ProtocolData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_data', models.JSONField(db_comment='Данные из стартового и финального протоколов', verbose_name='Данные из стартового и финального протоколов')),
                ('parsing_session', models.ForeignKey(db_comment='Сессия парсинга', on_delete=django.db.models.deletion.CASCADE, to='parsing.parsingsession', verbose_name='Сессия парсинга')),
            ],
            options={
                'verbose_name': 'данные по заплыву',
                'verbose_name_plural': 'Данные по заплывам',
            },
        ),
    ]
