# Generated by Django 5.0.6 on 2024-06-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsingsession',
            name='pool_length',
            field=models.CharField(choices=[('25m', '25m'), ('50m', '50m')], db_comment='Длина бассейна', default='25m', max_length=4, verbose_name='Длина бассейна'),
        ),
        migrations.AlterField(
            model_name='parsingsession',
            name='swim_length',
            field=models.CharField(choices=[('50m', '50m'), ('100m', '100m'), ('200m', '200m'), ('400m', '400m')], db_comment='Длина заплыва', default='100m', max_length=5, verbose_name='Длина заплыва'),
        ),
    ]
