# Generated by Django 5.0.6 on 2024-06-30 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0002_alter_parsingsession_pool_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocoldata',
            name='protocol_data',
        ),
        migrations.AddField(
            model_name='protocoldata',
            name='final_category',
            field=models.CharField(blank=True, db_comment='Категория финала', max_length=24, null=True, verbose_name='Категория финала'),
        ),
        migrations.AddField(
            model_name='protocoldata',
            name='final_position',
            field=models.IntegerField(blank=True, db_comment='Финишная позиция (место)', null=True, verbose_name='Финишная позиция (место)'),
        ),
        migrations.AddField(
            model_name='protocoldata',
            name='initials',
            field=models.CharField(db_comment='Фамилия Имя', default='Ошибка при парсинге', max_length=64, verbose_name='Фамилия Имя'),
        ),
        migrations.AddField(
            model_name='protocoldata',
            name='points',
            field=models.IntegerField(blank=True, db_comment='Очки', null=True, verbose_name='Очки'),
        ),
        migrations.AddField(
            model_name='protocoldata',
            name='reaction_time',
            field=models.TimeField(blank=True, db_comment='Время реакции', null=True, verbose_name='Время реакции'),
        ),
        migrations.AddField(
            model_name='protocoldata',
            name='result',
            field=models.TimeField(db_comment='Результат', default=datetime.time(0, 0), verbose_name='Результат'),
        ),
        migrations.AddField(
            model_name='protocoldata',
            name='result_100m',
            field=models.TimeField(blank=True, db_comment='Результат на 100м', null=True, verbose_name='100m'),
        ),
        migrations.AddField(
            model_name='protocoldata',
            name='result_150m',
            field=models.TimeField(blank=True, db_comment='Результат на 150м', null=True, verbose_name='150m'),
        ),
        migrations.AddField(
            model_name='protocoldata',
            name='result_200m',
            field=models.TimeField(blank=True, db_comment='Результат на 200м', null=True, verbose_name='200m'),
        ),
        migrations.AddField(
            model_name='protocoldata',
            name='result_250m',
            field=models.TimeField(blank=True, db_comment='Результат на 250м', null=True, verbose_name='250m'),
        ),
        migrations.AddField(
            model_name='protocoldata',
            name='result_300m',
            field=models.TimeField(blank=True, db_comment='Результат на 300м', null=True, verbose_name='300m'),
        ),
        migrations.AddField(
            model_name='protocoldata',
            name='result_350m',
            field=models.TimeField(blank=True, db_comment='Результат на 350м', null=True, verbose_name='350m'),
        ),
        migrations.AddField(
            model_name='protocoldata',
            name='result_400m',
            field=models.TimeField(blank=True, db_comment='Результат на 400м', null=True, verbose_name='400m'),
        ),
        migrations.AddField(
            model_name='protocoldata',
            name='result_50m',
            field=models.TimeField(blank=True, db_comment='Результат на 50м', null=True, verbose_name='50m'),
        ),
        migrations.AddField(
            model_name='protocoldata',
            name='start_position',
            field=models.IntegerField(blank=True, db_comment='Стартовая позиция (№ п.п.)', null=True, verbose_name='Стартовая позиция (№ п.п.)'),
        ),
        migrations.AddField(
            model_name='protocoldata',
            name='year_of_birth',
            field=models.IntegerField(blank=True, db_comment='Год рождения', null=True, verbose_name='Год рождения'),
        ),
    ]
