# Generated by Django 5.0.6 on 2024-06-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0003_remove_protocoldata_protocol_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsingsession',
            name='pool_length',
            field=models.CharField(choices=[('25m', '25m'), ('50m', '50m')], db_comment='Длина бассейна', default='50m', max_length=4, verbose_name='Длина бассейна'),
        ),
    ]
