# Generated by Django 5.0.6 on 2024-07-05 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0005_remove_protocoldata_result_100m_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(db_comment='Название настройки парсинга', max_length=256, verbose_name='Название настройки')),
                ('setting_value', models.CharField(db_comment='Значение настройки парсинга', max_length=256, verbose_name='Значение настройки')),
            ],
            options={
                'verbose_name': 'настройку парсинга',
                'verbose_name_plural': 'Настройки парсинга',
            },
        ),
        migrations.AlterField(
            model_name='swimsplittime',
            name='protocol_data',
            field=models.ForeignKey(db_comment='Данные заплыва', on_delete=django.db.models.deletion.CASCADE, to='parsing.protocoldata', verbose_name='Данные заплыва'),
        ),
    ]
