# Generated by Django 5.0.6 on 2024-07-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0008_averagespeed_beststartfinishpercentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimsplittime',
            name='distance',
            field=models.IntegerField(db_comment='Дистанция', verbose_name='Дистанция'),
        ),
    ]
