# Generated by Django 5.0.6 on 2024-07-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0010_numbercycles_data_pace_data_startdistance_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsingsettings',
            name='setting_value',
            field=models.IntegerField(db_comment='Значение настройки парсинга', verbose_name='Значение настройки'),
        ),
    ]
